DROP TABLE ship CASCADE;
DROP TABLE road CASCADE;
DROP TABLE activity CASCADE;
DROP TABLE radar CASCADE;
DROP TABLE moon CASCADE;
DROP TABLE signals CASCADE;
DROP TABLE reflection_log CASCADE;
DROP TYPE RADAR_TYPE;
DROP TYPE ROAD_LOCATION;